### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by rkarthur** [votinginfoproject/VIP-feed-information-project#19]
Hey, I'm a data journalist working on a story for VICE News about polling places. I'm wondering if there is a csv somewhere with the VIP information (location, hours of operation) on each polling place for past elections. I'm especially interested in the 2012 & 2016 elections. How would I go about getting that data?

**Comment by lbirdpew** [comment]
Hi Rob,

We do not provide raw data outside of the Google Civic Info API.  You may want to reach out to states you are interested in and ask them for a copy of their VIP feeds from past elections, however we are not able to provide them for you.  If you have any questions, please let me know.

Lester
